### PR TITLE
Trying to understand why we need this extra View.

### PR DESCRIPTION
**Pull request by rogerhu**
@nidhi1608 @nesquena 

need to get rid of the findViewById's...but wanted to get your opinion

### CODE REVIEW

**Comment by rogerhu** [comment]
Also need to update the lab to say something different from:

```
 // Set this as the background color for `vPalette`.
```

**Comment by nidhi1608** [comment]
If we remove this view, the shared element transition won't work the way it works now. You animate the palette from parent activity to details activity.

**Comment by rogerhu** [comment]
I think you need it since the phone # on the detail view isn't part of the overview page?

**Comment by nidhi1608** [comment]
Yes, if the views being animated were the same across both screens then we could have gotten rid of that extra view. But because of the phone no. we want it to be a separate view.

**Pull request closed without merging**
